[theme]
primaryColor = "#FF5733"       # Warna tombol & elemen utama
backgroundColor = "#F0F2F6"    # Warna latar belakang
secondaryBackgroundColor = "#E0E0E0"  # Warna sidebar
textColor = "#262730"          # Warna teks
font = "sans serif"            # Pilihan: "sans serif", "serif", "monospace"